version: "3.9"
services:
  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: dbimage
    container_name: node1
    tty: true
    ports:
      - "22"

  node2:
    image: dbimage
    depends_on:
      - node1
    container_name: node2
    tty: true
    ports:
      - "22"